import = ["~/.sesh.toml"]

[[session]]
name = "Neovim Config"
path = "~/repo/dot/nvim/_config/nvim"

[[session]]
name = "dotfiles"
path = "~/repo/dot"
startup_command = "lazygit"

[[session]]
name = "Downloads ðŸ“¥"
path = "~/Downloads"
startup_command = "la"
