# import = ["~/.sesh.toml"]

[default_sesion]
startup_command = "nvim -c ':Telescope find_files"

[[session]]
name = "Neovim Config"
path = "~/repo/dot/nvim/.config/nvim"

[[session]]
name = "dotfiles"
path = "~/repo/dot"
startup_command = "lazygit"

[[session]]
name = "Downloads ðŸ“¥"
path = "~/Downloads"
startup_command = "la"
